<?php
echo $this->headScript()
    ->prependFile(
        $this->basePath('js/application/atividade/formulario.js')
    );
?>

<div class="panel panel-default"  ng-controller="formularioAtividadeController">
    <div class="panel-heading">
    Atividades
    </div>
    <div class="panel-body">


        <form class="form-horizontal">
            <div class="form-group">
                <label for="ds_descricao" class="col-sm-2 control-label">
                Descrição
                </label>
                <div class="col-sm-10">
                    <input type="ds_descricao" ng-model="ds_descricao" class="form-control" id="ds_descricao" placeholder=""
                        ng-init="ds_descricao = '<?php echo $objAtividade->getDsDescricao(); ?>'">
                </div>
            </div>

            <div class="form-group">
                <label for="ds_detalhes" class="col-sm-2 control-label">
                Detalhes
                </label>
                <div class="col-sm-10">
                    <input type="ds_detalhes" ng-model="ds_detalhes" class="form-control" id="ds_detalhes" placeholder=""
                        ng-init="ds_detalhes = '<?php echo $objAtividade->getDsDetalhes(); ?>'">
                </div>
            </div>

            <div class="form-group">
                <label for="nr_ordem" class="col-sm-2 control-label">
                Ordem
                </label>
                <div class="col-sm-10">
                    <input type="nr_ordem" ng-model="nr_ordem" class="form-control" id="nr_ordem" placeholder=""
                        ng-init="nr_ordem = '<?php echo $objAtividade->getNrOrdem(); ?>'">
                </div>
            </div>

            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="button" class="btn btn-default" ng-click="enviarForm()">
                        <span class="glyphicon glyphicon-floppy-disk" aria-hidden="true" ng-click="enviarForm()"></span>
                        Salvar
                    </button>

                    <input type="hidden" ng-model="cd_atividade" class="form-control" id="cd_atividade" placeholder=""
                        ng-init="cd_atividade = '<?php echo $objAtividade->getCdAtividade(); ?>'">

                    <input type="hidden" ng-model="cd_processo" class="form-control" id="cd_processo" placeholder=""
                        ng-init="cd_processo = '<?php echo $cd_processo; ?>'">
                </div>
            </div>
        </form>


    </div>

    <div class="panel-footer">
        <button class="btn btn-info"
            type="button" id="dropdownMenu1" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="true" ng-click="voltar()" />

            <span class="glyphicon glyphicon-arrow-left" aria-hidden="true" ng-click="voltar()"></span>
    </div>
</div>

