<?php
echo $this->headScript()
    ->prependFile(
        $this->basePath('js/application/processo/formulario.js')
    );
?>

<div class="panel panel-default"  ng-controller="formularioProcessoController">
    <div class="panel-heading">
    Processos
    </div>
    <div class="panel-body">


        <form class="form-horizontal">
            <div class="form-group">
                <label for="ds_nome" class="col-sm-2 control-label">
                Nome
                </label>
                <div class="col-sm-10">
                    <input type="ds_nome" ng-model="ds_nome" class="form-control" id="ds_nome" placeholder=""
                        ng-init="ds_nome = '<?php echo $objProcesso->getDsNome(); ?>'">
                </div>
            </div>

            <div class="form-group">
                <label for="ds_descricao" class="col-sm-2 control-label">
                Descrição
                </label>
                <div class="col-sm-10">
                    <input type="ds_descricao" ng-model="ds_descricao" class="form-control" id="ds_descricao" placeholder=""
                        ng-init="ds_descricao = '<?php echo $objProcesso->getDsDescricao(); ?>'">
                </div>
            </div>

            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="button" class="btn btn-default" ng-click="enviarForm()">
                        <span class="glyphicon glyphicon-floppy-disk" aria-hidden="true" ng-click="enviarForm()"></span>
                        Salvar
                    </button>

                    <input type="hidden" ng-model="id" class="form-control" id="id" placeholder=""
                        ng-init="id = '<?php echo $objProcesso->getId(); ?>'">
                </div>
            </div>
        </form>


    </div>

    <div class="panel-footer">
        <button class="btn btn-info"
            type="button" id="dropdownMenu1" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="true" ng-click="voltar()" />

            <span class="glyphicon glyphicon-arrow-left" aria-hidden="true" ng-click="voltar()"></span>
    </div>
</div>

