<?php
echo $this->headScript()
    ->prependFile(
        $this->basePath('js/application/processo/formulario.js')
    );
?>

<div class="panel panel-default"  ng-controller="formularioProcessoController">
    <div class="panel-heading">
    Processos
    </div>
    <div class="panel-body">


        <form class="form-horizontal">
            <div class="form-group">
                <label for="ds_nome" class="col-sm-2 control-label">
                Nome
                </label>
                <div class="col-sm-10">
                    <input type="ds_nome" ng-model="ds_nome" class="form-control" id="ds_nome" placeholder="">
                </div>
            </div>

            <div class="form-group">
                <label for="ds_descricao" class="col-sm-2 control-label">
                Descrição
                </label>
                <div class="col-sm-10">
                    <input type="ds_descricao" ng-model="ds_descricao" class="form-control" id="ds_descricao" placeholder="">
                </div>
            </div>

            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="button" class="btn btn-default" ng-click="enviarForm()">Enviar</button>
                </div>
            </div>
        </form>


    </div>

    <div class="panel-footer">
        <span class="glyphicon glyphicon-pencil" aria-hidden="true"
            ng-click="adicionarNovo()"></span>
    </div>
</div>

