<?php
echo $this->headScript()
    ->prependFile(
        $this->basePath('js/application/processo/index.js')
    );
?>

<div class="panel panel-default"  ng-controller="indexProcessoController">
    <div class="panel-heading">
        Processos

        <button class="btn btn-info"
            type="button" id="dropdownMenu1" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="true" ng-click="adicionarNovo()" />

            <span class="glyphicon glyphicon-plus" aria-hidden="true" ng-click="adicionarNovo()"></span>
    </div>
    <div class="panel-body">
        <ul class="list-group">

        <li class="list-group-item" ng-repeat="arrDados in arrRegistros" >
            <a href="#" ng-click="executarProcesso(arrDados.id)">
            {{arrDados.ds_nome}}
            </a>
        </li>
        </ul>
    </div>
</div>

