<?php
echo $this->headScript()
    ->prependFile(
        $this->basePath('js/application/processo/index.js')
    );
?>

<div class="panel panel-default"  ng-controller="indexProcessoController">
    <div class="panel-heading">
    Processos <span class="glyphicon glyphicon-pencil" aria-hidden="true" ng-click="adicionarNovo()"></span>
    </div>
    <div class="panel-body">
        <ul class="list-group">
        <li class="list-group-item">Cras justo odio</li>
        <li class="list-group-item">Dapibus ac facilisis in</li>
        <li class="list-group-item">Morbi leo risus</li>
        <li class="list-group-item">Porta ac consectetur ac</li>
        <li class="list-group-item">Vestibulum at eros</li>
        </ul>
    </div>
</div>

