<?php
echo $this->headScript()
    ->prependFile(
        $this->basePath('js/application/processo/visualizar.js')
    );
?>

<div class="panel panel-default"  ng-controller="visualizarProcessoController">

    <div class="panel-heading">
        Processos

        <button class="btn btn-info"
            type="button" id="dropdownMenu1" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="true"
            ng-click="editarProcesso(<? echo $objProcesso->getCdProcesso(); ?>)"
            >
            <span class="glyphicon glyphicon-pencil" aria-hidden="true"
                ng-click=""></span>
        </button>

        <button class="btn btn-info"
            type="button" id="dropdownMenu1" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="true"
            ng-click="excluirProcesso(<? echo $objProcesso->getCdProcesso(); ?>)"
            >
            <span class="glyphicon glyphicon-remove-circle" aria-hidden="true"
                ng-click=""></span>
        </button>
    </div>

    <div class="panel-body">
        <b>
        Processo id:
        </b>
        <? echo $objProcesso->getCdProcesso(); ?>
        <br>
        <b>
        Título:
        </b>
        <? echo $objProcesso->getDsNome(); ?>
        <br><br>
        <b>
        Descrição:
        </b>
        <br>
        <? echo $objProcesso->getDsDescricao(); ?>
        <br />
        <br />




        <div class="panel panel-default "  ng-controller="visualizarProcessoController">
            <div class="panel-heading">
                <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                Atividades

                <button class="btn btn-info"
                    type="button" id="dropdownMenu2" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="true"
                    ng-click="novaAtividade(<? echo $objProcesso->getCdProcesso(); ?>)"
                    >
                    <span class="glyphicon glyphicon-pencil" aria-hidden="true"
                        ng-click=""></span>
                </button>

            </div>
            <div class="panel-body">
            teste
            </div>
        </div>


    </div>

    <div class="panel-footer">
        <button class="btn btn-info"
            type="button" id="dropdownMenu1" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="true" ng-click="voltar()" />

            <span class="glyphicon glyphicon-arrow-left" aria-hidden="true" ng-click="voltar()"></span>
    </div>
</div>

