<?php
echo $this->headScript()
    ->prependFile(
        $this->basePath('js/application/processo/visualizar.js')
    );
?>

<div class="panel panel-default"  ng-controller="visualizarProcessoController">

    <div class="panel-heading">
        Processos

        <button class="btn btn-info"
            type="button" id="btn_incluir"
            aria-haspopup="true" aria-expanded="true"
            ng-click="editarProcesso(<?php echo $objProcesso->getCdProcesso(); ?>)"
            data-toggle="tooltip" data-placement="bottom" title="Alterar Processo"
            >
            <span class="glyphicon glyphicon-pencil" aria-hidden="true"
                ng-click=""></span>
        </button>

        <button class="btn btn-info"
            type="button" id="btn_excluir"
            aria-haspopup="true" aria-expanded="true"
            ng-click="excluirProcesso(<?php echo $objProcesso->getCdProcesso(); ?>)"
            data-toggle="tooltip" data-placement="bottom" title="Excluir"
            >
            <span class="glyphicon glyphicon-remove-circle" aria-hidden="true"
                ng-click=""></span>
        </button>
    </div>

    <div class="panel-body">
        <b>
        Processo id:
        </b>
        <?php echo $objProcesso->getCdProcesso(); ?>
        <br>
        <b>
        Título:
        </b>
        <?php echo $objProcesso->getDsNome(); ?>
        <br><br>
        <b>
        Descrição:
        </b>
        <br>
        <?php echo $objProcesso->getDsDescricao(); ?>
        <br />
        <br />

        <div class="panel panel-default "  ng-controller="visualizarProcessoController">
            <div class="panel-heading">
                <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                Atividades

                <button class="btn btn-info"
                    type="button" id="btn_add"
                    aria-haspopup="true" aria-expanded="true"
                    ng-click="novaAtividade(<?php echo $objProcesso->getCdProcesso(); ?>)"
                    data-toggle="tooltip" data-placement="bottom" title="Adicionar Atividade"
                    >
                    <span class="glyphicon glyphicon-plus" aria-hidden="true"
                        ng-click=""></span>
                </button>

            </div>
            <div class="panel-body">
            <ul class="list-group">

            <?php
            foreach ($arrAtividades as $objAtividade) {
                ?>
                <li class="list-group-item">

                    <?php
                    echo $objAtividade->getDsDescricao();
                    ?>

                </li>
                <?php
            }
            ?>
            </ul>

            </div>
        </div>


    </div>

    <div class="panel-footer">
        <button class="btn btn-info"
            type="button" id="dropdownMenu1" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="true" ng-click="voltar()" />

            <span class="glyphicon glyphicon-arrow-left" aria-hidden="true" ng-click="voltar()"></span>
    </div>
</div>

