# config/yaml/Processo.dcm.yml
Application\Entity\Processo:
  type: entity
  table: processo
  id:
    cd_processo:
      type: integer
      generator:
        strategy: AUTO
  fields:
    ds_nome:
      type: string
    ds_descricao:
        type: string
oneToMany:
    arrObjAtividades:
        targetEntity: Application\Entity\Atividade
        mappedBy: cd_processo