# config/yaml/User.dcm.yml
Application\Entity\User:
  type: entity
  table: user
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    nome:
      type: string
    login:
        type: string
    senha:
        type: string