# config/yaml/User.dcm.yml
Application\Entity\User:
  type: entity
  table: user
  id:
    cd_usuario:
      type: integer
      generator:
        strategy: AUTO
  fields:
    ds_nome:
      type: string
    ds_login:
        type: string
    ds_senha:
        type: string