# config/yaml/Processo.dcm.yml
Application\Entity\Processo:
  type: entity
  table: processo
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    ds_nome:
      type: string
    ds_descricao:
        type: string