# config/yaml/Atividade.dcm.yml
Application\Entity\Atividade:
    type: entity
    table: atividade
    id:
        cd_atividade:
            type: integer
            generator:
               strategy: AUTO
    fields:
        ds_descricao:
            type: string
        ds_detalhes:
            type: string
        nr_ordem:
            type: integer
    manyToOne:
        objProcesso:
            targetEntity: Application\Entity\Processo
            inversedBy: arrObjAtividades
            joinColumn:
                name: cd_processo
                referencedColumnName: cd_processo